name: Tests

on:
  push:
    branches:
      - master

  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      max-parallel: 1
      matrix:
        ruby:
          - '3.1.4'
          - '3.2.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        TEST_HTTP_URL: ${{ secrets.TEST_HTTP_URL }}
        TEST_PG_URL: ${{ secrets.TEST_PG_URL }}
        TEST_MYSQL_URL: ${{ secrets.TEST_MYSQL_URL }}
      run: bundle exec rake
